#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// These constants added manually because bindgen doesn't like to parse the '#define' statements
// for them

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

pub const OTF2_UNDEFINED_UINT8: u8 = !0u8;
pub const OTF2_UNDEFINED_INT8: i8 = !(OTF2_UNDEFINED_UINT8 >> 1) as i8;
pub const OTF2_UNDEFINED_UINT16: u16 = !0u16;
pub const OTF2_UNDEFINED_INT16: i16 = !(OTF2_UNDEFINED_UINT16 >> 1) as i16;
pub const OTF2_UNDEFINED_UINT32: u32 = !0u32;
pub const OTF2_UNDEFINED_INT32: i32 = !(OTF2_UNDEFINED_UINT32 >> 1) as i32;
pub const OTF2_UNDEFINED_UINT64: u64 = !0u64;
pub const OTF2_UNDEFINED_INT64: i64 = !(OTF2_UNDEFINED_UINT64 >> 1) as i64;
pub const OTF2_UNDEFINED_TYPE: u8 = OTF2_UNDEFINED_UINT8;
pub const OTF2_UNDEFINED_TIMESTAMP: u64 = OTF2_UNDEFINED_UINT64;
pub const OTF2_UNDEFINED_IO_PARADIGM: OTF2_IoParadigmRef = OTF2_UNDEFINED_UINT8;
pub const OTF2_UNDEFINED_STRING: OTF2_StringRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_ATTRIBUTE: OTF2_AttributeRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_SYSTEM_TREE_NODE: OTF2_SystemTreeNodeRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_LOCATION_GROUP: OTF2_LocationGroupRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_LOCATION: OTF2_LocationRef = OTF2_UNDEFINED_UINT64;
pub const OTF2_UNDEFINED_REGION: OTF2_RegionRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_CALLSITE: OTF2_CallsiteRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_CALLPATH: OTF2_CallpathRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_GROUP: OTF2_GroupRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_METRIC_MEMBER: OTF2_MetricMemberRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_METRIC: OTF2_MetricRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_COMM: OTF2_CommRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_PARAMETER: OTF2_ParameterRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_RMA_WIN: OTF2_RmaWinRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_CART_DIMENSION: OTF2_CartDimensionRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_CART_TOPOLOGY: OTF2_CartTopologyRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_SOURCE_CODE_LOCATION: OTF2_SourceCodeLocationRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_CALLING_CONTEXT: OTF2_CallingContextRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_INTERRUPT_GENERATOR: OTF2_InterruptGeneratorRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_IO_FILE: OTF2_IoFileRef = OTF2_UNDEFINED_UINT32;
pub const OTF2_UNDEFINED_IO_HANDLE: OTF2_IoHandleRef = OTF2_UNDEFINED_UINT32;
